name: Check PR Tasks

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-tasks:
    runs-on: ubuntu-latest
    - name: Check if all tasks are completed
      run: |
        if grep -q "\- \[ \]" "${{ github.event.pull_request.body }}"; then
          echo "❌ Not all tasks are completed in the PR description."
          exit 1
        else
          echo "✅ All tasks are completed in the PR description."
        fi
